#application: teak-spot-88306
#version: 2
runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /user_guide
  static_dir: CodeIgniter-3.1.6/user_guide

#- url: /assets/js/*
#  static_dir: CodeIgniter-3.1.6/assets/js

#- url: /assets/css/*
#  static_dir: CodeIgniter-3.1.6/assets/css

#- url: /assets/images/*
#  static_dir: CodeIgniter-3.1.6/assets/images

- url: /
  script: CodeIgniter-3.1.6/index.php

- url: /(.+)
  script: CodeIgniter-3.1.6/index.php
